[package]
name = "demo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.24", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.10"
prost = "0.12"

[build-dependencies]
tonic-build = "0.10"
